blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [ 
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls'))
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('new-post/', views.post_new, name="new-post"),
    path('category/<str:cats>/', views.CategoryView, name="category"),
    path('categories-list', views.CategoriesListView, name="categories-list"),
    path('<slug:slug>', views.post_page, name="page"),
    path('update/<slug:slug>', views.post_update, name="update"),
    path('delete/<slug:slug>/', views.post_delete, name="delete"),
    path('<slug:slug>/comment/', views.create_comment, name="comment"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.

    
class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(default="Esta categoria não possui descrição")
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    category = models.ManyToManyField(Category, related_name='posts')

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    date = models.DateTimeField(auto_now_add=True)
    body = models.CharField(max_length=255)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from. import models
from django.forms import ModelForm

class CreatePost(forms.ModelForm):
    category = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=models.Category.objects.all())
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'slug', 'category', 'banner']
        

class CommentForm(ModelForm):
    class Meta:
        model = models.Comment
        fields = ['body']

blog/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment, Category
from django.contrib.auth.decorators import login_required, permission_required
from. import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import CommentForm

# Create your views here.

#ListView
@login_required(login_url="/users/login/")
def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', { 'posts': posts})

#DetailView
@login_required(login_url="/users/login/")
def post_page(request, slug):
    #post = Post.objects.get(slug=slug)
    post = get_object_or_404(Post, slug=slug)
    comments = Comment.objects.filter(post=post.id).order_by('-date')
    categories = post.category.all()
    return render(request, 'posts/post_page.html', { 'post': post, 'comments':comments, 'categories':categories })

#CreateView
@login_required(login_url="/users/login/")
def post_new(request):
    if request.method == "POST":
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            newpost.category.set(form.cleaned_data.get("category"))
            newpost.save()
            return redirect("posts:list")
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', { 'form':form })

#UpdateView
@login_required(login_url="/users/login/")
#@permission_required('posts.update_post')
def post_update(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if post.author != request.user and not request.user.is_superuser:
            return HttpResponseRedirect(reverse('posts:page', args=(post.slug, )))
    if request.method == "POST":
        post.title = request.POST['title']
        post.body = request.POST['body']
        post.save()
        return HttpResponseRedirect(reverse('posts:page', args=(post.slug, )))
    return render(request, 'posts/post_update.html', { 'post':post })

#DeleteView
@login_required(login_url="/users/login/")
def post_delete(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if post.author != request.user and not request.user.is_superuser:
            return HttpResponseRedirect(reverse('posts:page', args=(post.slug, )))
    if request.method == "POST": 
        post.delete()
        return HttpResponseRedirect(reverse("posts:list"))
    return render(request, 'posts/post_delete.html', { 'post':post })

@login_required(login_url="/users/login/")
def create_comment(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = request.user
            comment_body = form.cleaned_data['body']
            comment = Comment(author=comment_author, body=comment_body, post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('posts:page', args=(post.slug, )))
    else:
        form = CommentForm()
    return render(request, 'posts/comment.html', {'form': form, 'post': post })

@login_required(login_url="/users/login/")
def CategoryView(request, cats):
    cat = get_object_or_404(Category, name=cats)
    cat_id = Category.objects.get(name=cats).id
    category_posts = Post.objects.filter(category=cat_id)
    return render(request, 'posts/categories.html', { 'cats':cats, 'category_posts':category_posts })

@login_required(login_url="/users/login/")
def CategoriesListView(request):
    categories = Category.objects.all()
    return render(request, 'posts/categories_list.html', { 'categories':categories })

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", { "form": form })

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", { "form": form })

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:list")

posts/templates/posts/categories.html
{% extends 'layout.html' %}

{% block title %}
    Posts 
{% endblock %}


{% block content %}
    <section>
        <h1>Posts</h1>
        <p>(Filtrando por: {{ cats }})</p>
        {% if category_posts %}
            {% for post in category_posts %}
                <article class="post">
                    <h2>
                        <a href="{% url 'posts:page' slug=post.slug %}">
                            {{ post.title }}
                        </a>
                    </h2>
                    <p>{{ post.date }} por {{ post.author }}</p>
                </article>
            {% endfor %}
        {% else %}
        <P> Nenhum post encontrado com essa categoria. </p>
        {% endif %}
    </section>
{% endblock %}

posts/templates/posts/categories_list.html
{% extends 'layout.html' %}

{% block title %}
    Categories
{% endblock %}


{% block content %}
    <section>
        <h1>Categorias</h1>
        <div class="category-div">
            {% for category in categories %}
                <div class="category"><a class="category-link" href="{% url 'posts:category' category.name %}">{{ category.name }}</a></div>
                <p>- {{ category.description }}</p>
            {% endfor %}
        </div>
    </section>
{% endblock %}

posts/templates/posts/comment.html
{% extends 'layout.html' %}

{% block content %}
<h2>Comentar em: {{ post.title }}</h2>

<form action="{% url 'posts:comment' post.slug %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="comment-button" type="submit">Comentar</button>
</form>

<p><a href="{% url 'posts:page' post.slug %}">Voltar para o post</a></p>
{% endblock content %}

posts/templates/posts/post_delete.html
{% extends 'layout.html' %}
{% block content %}
<form action="{% url 'posts:delete' post.slug %}" method="post">
  {% csrf_token %}
  <p>
    Você tem certeza que deseja excluir o post "{{ post.title }}"?
  </p>
  <button type="submit">Excluir
</form>
{% endblock content %}

posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
    New Post
{% endblock %}

{% block content %}
    <section>
        <h1>New Post</h1>
        <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Criar Post</button>
        </form>
    </section>
{% endblock %}

posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }} 
{% endblock %}

{% block content %}
    <section>
        <img class="banner" src="{{ post.banner.url }}" alt="{{ post.title }}"/>
        <h1>{{ post.title }}</h1>
        <p>{{ post.date }} por {{ post.author }}</p>
        <div class="category-div">
        {% for category in categories %}
            <div class="category"><a class="category-link" href="{% url 'posts:category' category.name %}">{{ category.name }}</div>
        {% endfor %}
        </div>

        {% if request.user == post.author or request.user.is_superuser%}
            <ul>
                <li><a href="{% url 'posts:update' post.slug %}">Editar</a></li>
                <li><a href="{% url 'posts:delete' post.slug %}">Excluir</a></li>
            </ul>
        {% endif %}
        
        <p>{{ post.body }}</p>
    </section>
    <section>
        <header class="comentarios">
            <h3>Comentários</h3>
            <a href="{% url 'posts:comment' post.slug %}"><button class="comment-button">Comentar</button></a>
        </header>
        <ul>
            {% if comments %}
                {% for comment in comments %}
                    <figure>
                        <figcaption>{{ comment.author }} em {{ comment.date }}</figcaption>
                        <blockquote>
                            - {{ comment.body }}
                        </blockquote>
                        
                    </figure>
                {% endfor %}
            {% else %}
                <p>Este post não possui comentários</p>
            {% endif %}
        </ul>
    </section>
{% endblock %}

posts/templates/posts/post_update.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }} 
{% endblock %}

{% block content %}
<h2>Atualizar Post: {{ post.title }}</h2>
<form method="post" action="{% url 'posts:update' post.slug%}" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
      <label for="id_title">Título:
      <input type="text" name="title" id="id_title" value="{{ post.title }}" />
    </p>
    <p>
        <label for=" id_body">Conteúdo:
        <input type="text" name="body" id="id_body" value="{{ post.body }}" />
    </p>
    <button type="submit">Atualizarbutton
</form>

{% endblock content %}

posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts 
{% endblock %}


{% block content %}
    <section>
        <h1>Posts</h1>
        {% for post in posts %}
            <article class="post">
                <h2>
                    <a href="{% url 'posts:page' slug=post.slug %}">
                         {{ post.title }}
                    </a>
                </h2>
                <p>{{ post.date }} por {{ post.author }}</p>
            </article>
        {% endfor %}
    </section>
{% endblock %}

templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Sobre este site</p>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>Página inicial do blog</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
       <h1>Blog</h1>
    <nav>
        <a class="nav-element" href="/">Home</a> 
        <a class="nav-element" href="/about">About</a>
        <a class="nav-element" href="{% url 'posts:list' %}">Posts</a>
        {% if user.is_authenticated %}
            <a class="nav-element" href="{% url 'posts:new-post' %}">Criar</a>
            <a class="nav-element" href="{% url 'posts:categories-list' %}">Categorias</a>
            <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button class="logout-button">Logout ({{ user.username }})</button>
            </form>
        {% else %}
            <a class="nav-element" href="{% url 'users:register' %}">Registro</a>
            <a class="nav-element" href="{% url 'users:login' %}">Login</a>
        {% endif %}
    </nav> 
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    User Login 
{% endblock %}

{% block content %}
        <h1>User Login</h1>
        <form class="form-with-validation" action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}" />
            {% endif %}
            <button class="form-submit">Submit</button>
        </form>
{% endblock %}

users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User 
{% endblock %}

{% block content %}
        <h1>Register a New User</h1>
        <form class="form-with-validation" action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Submit</button>
        </form>
{% endblock %}